version: '3'
services:
    client_web:
        # image: todos:react-client
        build:
            context: .
            dockerfile: ./docker_configs/client/Dockerfile
        ports:
            - 3000:80
    node_web:
        # image: todos:node-server
        build:
            context: .
            dockerfile: ./docker_configs/server/Dockerfile
        ports: 
            - 8050:8050
        depends_on: 
            - postgres_db
            - adminer

    postgres_db:
        image: postgres:alpine
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: todos

    adminer:
        image: adminer
        depends_on: 
            - postgres_db
        ports:
            - 8080:8080
        environment: 
            ADMINER_DESIGN: mvt