version: '3'
services:
    node_web:
        image: node:alpine
        volumes: 
            - ./todos:/todos
        ports: 
            - 8050:8050
        depends_on: 
            - postgres_db
            - adminer
        command: ["/bin/sh"]

    postgres_db:
        image: postgres:alpine
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: todos

    adminer:
        image: adminer
        depends_on: 
            - postgres_db
        ports:
            - 8080:8080
        environment: 
            ADMINER_DESIGN: mvt